Update travis script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,10 +1,17 @@
 sudo: false
+
 dist: trusty
 
 language: php
 
-before_install:
-  - phpenv config-rm xdebug.ini
+php:
+    - 5.4
+    - 5.5
+    - 5.6
+    - 7.0
+    - 7.1
+    - 7.2
+    - nightly
 
 notifications:
   email:
@@ -36,20 +43,25 @@ matrix:
     - php: 5.6
       env: WP_VERSION=latest WP_MULTISITE=1
 
-before_script:
-  - export PATH="$HOME/.composer/vendor/bin:$PATH"
-  - if [[ "$SNIFF" == "1" ]]; then
-      composer global require wp-coding-standards/wpcs;
-      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs;
-      phpcs --config-set standard infinum;
-    fi
+  allow_failures:
+    # Allow failures for unstable builds.
+    - php: nightly
+
+before_install:
+  # Speed up build time by disabling Xdebug.
+  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
+  # https://twitter.com/kelunik/status/954242454676475904
+  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
+  # Install PHP CodeSniffer.
+  - if [[ "$SNIFF" == "1" ]]; then composer self-update; fi
+  - if [[ "$SNIFF" == "1" ]]; then composer require wp-coding-standards/wpcs; fi
+  - if [[ "$SNIFF" == "1" ]]; then composer require wimg/php-compatibility; fi
+  - if [[ "$SNIFF" == "1" ]]; then composer require dealerdirect/phpcodesniffer-composer-installer; fi
+  - if [[ "$SNIFF" == "1" ]]; then composer install; fi
+  - phpenv rehash
 
 script:
-  # Search theme for PHP syntax errors.
-  - find . \( -name '*.php' \) -exec php -lf {} \;
-  - |
-    if [[ "$SNIFF" == "1" ]]; then
-      composer global require wp-coding-standards/wpcs;
-      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs;
-      phpcs --config-set standard infinum;
-    fi
+  # Search for PHP syntax errors.
+  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
+  # Run PHPCS.
+  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs . --extensions=php --runtime-set ignore_warnings_on_exit 1; fi
